### ISSUE TITLE
Answering a question should be done via AJAX

### ISSUE THREAD

**Issue by alexstojda** [alexstojda/SOEN341#65]
[Priority: Low, Risk: Low]

**Comment by bnduwi** [comment]
I have been watching some video's on how AJAX is done. Seems like there is some JQuery involved from what I've seen. I'll attempt to make the AJAX happen. So just to be sure the AJAX part is to just update the page to display the answer without loading the entire page. When this is done the answer should be saved to DB. How does the save work is it a separate file that gets called for this.

**Comment by alexstojda** [comment]
@bnduwi 

Here is the process for the Ajax : 

1. Keep your form as it is, but using jQuery, add an event listener to the button using `.click()`. In the body of the anonymous function you'll create, add `event.preventDefault();` to prevent the form from doing it's default action. 

2. In the function, use `$.ajax()` to make a POST request to the controller. 

3. On the controller side, everything should stay the same, except instead of rendering the view, send back a JSON response with the updated vote count. 

4. Back in the onclick function, take the JSON response and use it to update the votes on the page. 

5. Profit

**Comment by bnduwi** [comment]
Ok thanks for the clarification.
