### ISSUE TITLE
As an unauthenticated user I should be able to search through all the questions/answers that exist on the website

### ISSUE THREAD

**Issue by PeterGhimself** [alexstojda/SOEN341#68]
[Priority: Low, Risk: Low]

Ideally we'd have a search bar with some place holder text such as "Search..." and a button labeled "search" that onclick (or on enter if search input field is focused) would redirect to a page showing all the questions and answers that contain text that matches the string being searched by the user.

Acceptance test:
- [ ] I am able to search through answers and questions.

**Comment by PeterGhimself** [comment]
Made some wireframes using mockflow, In terms of UI, I guess it comes down to:
1. Altering the homepage to add the search bar (all though I suppose we'd want to add it to most other pages too)

![soen341-uc4_homepage](https://user-images.githubusercontent.com/19865282/36648601-929d3790-1a63-11e8-8312-95c92255659d.png)

2. Adding a new search result page to display results
![soen341-uc4search_result_page](https://user-images.githubusercontent.com/19865282/36648602-92b48ff8-1a63-11e8-81ea-3954934e1475.png)

**Comment by alexstojda** [comment]
Love the wireframes! I think the bulk of the task is making the search part work. 

Make it a super simple SQL query that matches either the title of the question or body. 

e.g. `SELECT * FROM 'questions' WHERE title LIKE %keyword% OR body LIKE %keyword%`
