### ISSUE TITLE
As an authenticated user, I input fields on the site using a rich text editor

### ISSUE THREAD

**Issue by alexstojda** [alexstojda/SOEN341#71]
As an authenticated user, I can format my question or answer using a rich text editor.

**Comment by WindOfRussia** [comment]
changed to fields to cover Qs, As and the comments. 👍

**Comment by alexstojda** [comment]
@WindOfRussia  comments will not have formating. Only, Questions and Answers.

**Comment by alexstojda** [comment]
Editors I like so far
https://github.com/nhnent/tui.editor
https://github.com/steveathon/bootstrap-wysiwyg

**Comment by WindOfRussia** [comment]
@alexstojda so confirm feature complete and close this epic.
