### ISSUE TITLE
Submit Question & Answers unit tests (Backend)

### ISSUE THREAD

**Issue by PeterGhimself** [alexstojda/SOEN341#80]
- [x] Backend tests
- - [x] Questions done
- - [x] Answers done

**Comment by PeterGhimself** [comment]
started development on branch  [Issue-80](/alexstojda/SOEN341/tree/Issue80)

**Comment by PeterGhimself** [comment]
Not sure why, but for some reason even though the browser question creation test in my last commit ed0227a runs with no failures when I run it by itself, but when I run it with all the other tests it gives me errors relating to dusk attributes not being found and PCRE patterns not matching (other tests affected: testQuestionVote, testAnswerVote, testBasicExample, testLogin)

**Comment by alexstojda** [comment]
@PeterGhimself  I created a new issue for Sprint 4 to do the backend tests since it proved to be too many points for this sprint.

**Comment by PeterGhimself** [comment]
@alexstojda I have rolled this branch back to 60679f9 and force pushed. It passes CI, so I will open a PR.

**Comment by WindOfRussia** [comment]
@PeterGhimself  @alexstojda  this issue needs estimates. and maybe should be part of a "unit tests" epic
